---
- name: DEPLOY -> redis
  hosts: redis
  gather_facts: false
  vars_files:
    - ../env_vars/base.yml

  tasks:
    - name: Extract part of hostname to determine container name
      set_fact:
        redis_role: "{{ inventory_hostname.split('-')[2] }}"
    
    - name: Turning off secondary for redis by deleting redis_replica.conf
      copy:
        dest: "/srv/newsblur/docker/redis/redis_{{ redis_role }}_replica.conf"
        content: ""
      tags:
        - never
        - replicaofnoone

    - name: Setting Redis REPLICAOF NO ONE
      shell: docker exec redis redis-cli REPLICAOF NO ONE
      tags:
        - never
        - replicaofnoone
