---
# File: main.yml - Handlers for Consul

- name: reload consul configuration
  become: yes
  service:
    name: consul
    state: reloaded
  listen: reload consul

- name: restart redis user
  become: yes
  command: docker restart redis_user
  listen: restart redis_user
- name: restart redis story
  become: yes
  command: docker restart redis_story
  listen: restart redis_story
- name: restart redis session
  become: yes
  command: docker restart redis_session
  listen: restart redis_session
- name: restart redis pubsub
  become: yes
  command: docker restart redis_pubsub
  listen: restart redis_pubsub
