name: Android CI
defaults:
  run:
    working-directory: clients/android/NewsBlur

on:
  push:
    branches:
      - sictiru

jobs:
  build-and-unit-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Unit Test
        run: ./gradlew -Pci --console=plain :app:testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
